name: scrape-boxscore

# 1) Запуск вручную (кнопка "Run workflow")
# 2) Автоматически каждую минуту
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем содержимое репозитория
      - uses: actions/setup-node@v4
  with:
    node-version: '20'
- run: npm install node-fetch@2

      # Запускаем наш скрипт, который тянет данные с ESPN
      - run: node scrape.js

      # Добавляем/обновляем файл live/box.json и делаем коммит
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'live/box.json'
          message: 'auto: update box'
