name: scrape-boxscore

on:
  workflow_dispatch:      # запуск вручную по кнопке
  schedule:
  - cron: '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'             # ← важно! v20 поддерживает fetch без пакетов

      - run: node scrape.js              # запускаем наш скрипт

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'live/box.json'
          message: 'auto: update box'
