name: scrape-boxscore

on:
  workflow_dispatch:

jobs:
  fetch-boxscore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run scrape.js
        run: node scrape.js
        env:
          GAME_ID: ${{ secrets.GAME_ID }}
          LEAGUE: ${{ secrets.LEAGUE }}

      - name: Commit box.json (если он появился)
        run: |
          if [ -f live/box.json ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add live/box.json
            git commit -m "auto: update box"
            git push
          else
            echo "⚠️ box.json не найден — матч ещё не стартовал или ESPN вернул пустоту"
          fi
